[versions]
sonarqube = "7.5.0.8588"
java = "25"

spring-boot = "4.1.1"
spring-dependency-management = "1.1.7"
ktlint-plugin = "14.2.0"
ktlint-engine = "1.8.0"
detekt-plugin = "2.0.0-alpha.6"
dokka-plugin = "2.2.0"
kotlin = "2.4.10"

kotlin-logging = "8.0.4"
swagger = "2.2.55"

[libraries]
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server" }

springframework-tx = { module = "org.springframework:spring-tx" }

spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }

swagger-core-models = { module = "io.swagger.core.v3:swagger-models", version.ref = "swagger" }

jakarta-servlet-api = { module = "jakarta.servlet:jakarta.servlet-api" }
jackson-databind = { module = "tools.jackson.core:jackson-databind" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }

kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-security-test = { module = "org.springframework.security:spring-security-test" }

spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
detekt = { id = "dev.detekt", version.ref = "detekt-plugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka-plugin" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }

[bundles]
web-api = [
    "spring-boot-starter-oauth2-resource-server",
    "spring-boot-starter-security",
]

test-common = [
    "kotlin-test-junit5",
    "spring-boot-starter-test",
    "spring-boot-starter-security-test",
]
