[versions]
sonarqube = "7.5.0.8588"
java = "25"

spring-boot = "4.1.1"
spring-dependency-management = "1.1.7"
ktlint-plugin = "14.2.0"
detekt-plugin = "2.0.0-alpha.6"
dokka-plugin = "2.2.0"
kotlin = "2.4.10"

testcontainers = "2.0.5"
kotlin-logging = "8.0.4"
avro = "1.12.2"
confluent = "8.3.2"

[libraries]
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-jackson = { module = "org.springframework.boot:spring-boot-starter-jackson" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }

spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }

springframework-kafka = { module = "org.springframework.kafka:spring-kafka" }
springframework-kafka-test = { module = "org.springframework.kafka:spring-kafka-test" }

jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin" }

apache-avro = { module = "org.apache.avro:avro", version.ref = "avro" }
confluent-kafka-avro-serializer = { module = "io.confluent:kafka-avro-serializer", version.ref = "confluent" }

kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }

kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-security-test = { module = "org.springframework.security:spring-security-test" }

testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter" }
testcontainers-kafka = { module = "org.testcontainers:testcontainers-kafka" }

springframework-web = { module = "org.springframework:spring-web" }

spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
detekt = { id = "dev.detekt", version.ref = "detekt-plugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka-plugin" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }

[bundles]
spring-boot-common = [
    "spring-boot-starter",
    "kotlin-reflect",
    "kotlin-stdlib-jdk8",
    "spring-boot-starter-jackson",
    "jackson-module-kotlin",
    "springframework-kafka",
    "kotlin-logging"
]

test-common = [
    "kotlin-test-junit5",
    "spring-boot-starter-test",
    "springframework-kafka-test",
    "testcontainers-junit-jupiter",
    "testcontainers-kafka",
    "spring-boot-starter-security-test",
]

messaging-api = [
    "spring-boot-starter-data-jpa",
    "springframework-web",
]
