spring:
  mvc:
    problemdetails:
      enabled: true
  webflux:
    problemdetails:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}
          audiences:
            - veds-api

application:
  shared:
    keycloak:
      server-url: ${KEYCLOAK_SERVER_URL}
      realm: ${KEYCLOAK_REALM}
      admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
      admin-client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
      gateway-client-id: ${KEYCLOAK_GATEWAY_CLIENT_ID}
      gateway-client-secret: ${KEYCLOAK_GATEWAY_CLIENT_SECRET}
      roles-claim-path: realm_access.roles
      cookie:
        refresh-token-cookie-name: KEYCLOAK_REFRESH_TOKEN
        http-only: true
        secure: ${COOKIE_SECURE:true}
        same-site: Strict
        path: "/"
