[versions]
sonarqube = "7.5.0.8588"
java = "25"
spring-boot = "4.1.1"
spring-dependency-management = "1.1.7"
ktlint-plugin = "14.2.0"
ktlint-engine = "1.8.0"
detekt-plugin = "2.0.0-alpha.6"
dokka-plugin = "2.2.0"
kotlin = "2.4.10"

[libraries]
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
springframework-web = { module = "org.springframework:spring-web" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
detekt = { id = "dev.detekt", version.ref = "detekt-plugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka-plugin" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
