[versions]
java = "25"
ktlint-plugin = "14.2.0"
detekt-plugin = "2.0.0-alpha.6"
kotlin = "2.4.10"
archunit = "1.5.1"
junit = "6.1.3"

[libraries]
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
detekt = { id = "dev.detekt", version.ref = "detekt-plugin" }
