spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL}
    security:
      protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
    ssl:
      trust-store-location: ${KAFKA_SSL_TRUSTSTORE_LOCATION:}
      trust-store-type: ${KAFKA_SSL_TRUSTSTORE_TYPE:PKCS12}
      trust-store-password: ${KAFKA_SSL_TRUSTSTORE_PASSWORD:}
    consumer:
      auto-offset-reset: earliest
