spring:

  datasource:
    url: jdbc:postgresql://localhost:5437/notification_service
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    validate-on-migrate: true

  kafka:
    consumer:
      group-id: notification-service-group

server:
  port: 8086

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    url: /api-docs
    config-url: /api-docs/swagger-config

application:
  translation:
    client:
      base-url: http://localhost:8087

logging:
  level:
    ROOT: INFO
    com.vertyll.veds: DEBUG
    org.springframework.security: DEBUG
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
