spring:

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  kafka:
    consumer:
      group-id: translation-service-group

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    validate-on-migrate: true
    clean-disabled: true

server:
  port: ${SERVER_PORT:8087}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

application:
  authz:
    client:
      base-url: ${IAM_SERVICE_URL}

logging:
  level:
    ROOT: WARN
    com.vertyll.veds: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
