name: API Gateway

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - "api-gateway/**"
      - "shared-web/**"
      - "shared-archunit/**"
      - "shared-authz/**"
      - "shared-error/**"
      - ".github/workflows/api-gateway.yml"
      - ".github/workflows/_image.yml"
      - ".github/workflows/quality-checks.yml"
  pull_request:
    branches:
      - main
    paths:
      - "api-gateway/**"
      - "shared-web/**"
      - "shared-archunit/**"
      - "shared-authz/**"
      - "shared-error/**"
      - ".github/workflows/api-gateway.yml"
      - ".github/workflows/_image.yml"
      - ".github/workflows/quality-checks.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Quality
    uses: ./.github/workflows/quality-checks.yml
    with:
      service: api-gateway
    secrets: inherit

  image:
    name: Image
    needs: quality
    if: github.event_name != 'push' || github.ref_type == 'tag'
    uses: ./.github/workflows/_image.yml
    with:
      context: .
      dockerfile: ./api-gateway/Dockerfile
      image-name: vertyll/veds-api-gateway
      tag-prefix: v
    secrets: inherit
