name: Notification Service

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - "notification-service/**"
      - "shared-web/**"
      - "shared-error/**"
      - "shared-archunit/**"
      - "shared-translation-client/**"
      - "shared-messaging-kafka/**"
      - "notification-contracts/**"
      - "project-contracts/**"
      - "task-contracts/**"
      - "mail-contracts/**"
      - "iam-contracts/**"
      - "contracts/**"
      - "shared-translation/**"
      - ".github/workflows/notification-service.yml"
      - ".github/workflows/_image.yml"
      - ".github/workflows/quality-checks.yml"
  pull_request:
    branches:
      - main
    paths:
      - "notification-service/**"
      - "shared-web/**"
      - "shared-error/**"
      - "shared-archunit/**"
      - "shared-translation-client/**"
      - "shared-messaging-kafka/**"
      - "notification-contracts/**"
      - "project-contracts/**"
      - "task-contracts/**"
      - "mail-contracts/**"
      - "iam-contracts/**"
      - "contracts/**"
      - "shared-translation/**"
      - ".github/workflows/notification-service.yml"
      - ".github/workflows/_image.yml"
      - ".github/workflows/quality-checks.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Quality
    uses: ./.github/workflows/quality-checks.yml
    with:
      service: notification-service
      hexagonal: true
    secrets: inherit

  image:
    name: Image
    needs: quality
    if: github.event_name != 'push' || github.ref_type == 'tag'
    uses: ./.github/workflows/_image.yml
    with:
      context: .
      dockerfile: ./notification-service/Dockerfile
      image-name: vertyll/veds-notification-service
      tag-prefix: v
    secrets: inherit
