name: Provisioner

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - "infra/kafka/**"
      - "infra/provisioner/**"
      - "contracts/**"
      - "scripts/schema_registry/**"
      - ".github/workflows/provisioner.yml"
      - ".github/workflows/_image.yml"
  pull_request:
    branches:
      - main
    paths:
      - "infra/kafka/**"
      - "infra/provisioner/**"
      - "contracts/**"
      - "scripts/schema_registry/**"
      - ".github/workflows/provisioner.yml"
      - ".github/workflows/_image.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image:
    name: Image
    if: github.event_name != 'push' || github.ref_type == 'tag'
    uses: ./.github/workflows/_image.yml
    with:
      context: .
      dockerfile: ./infra/provisioner/Dockerfile
      image-name: vertyll/veds-provisioner
      tag-prefix: v
    secrets: inherit
