name: Shared Messaging Kafka

on:
  push:
    branches:
      - main
    paths:
      - "shared-messaging-kafka/**"
      - ".github/workflows/shared-messaging-kafka-checks.yml"
      - ".github/workflows/quality-checks.yml"
  pull_request:
    branches:
      - main
    paths:
      - "shared-messaging-kafka/**"
      - ".github/workflows/shared-messaging-kafka-checks.yml"
      - ".github/workflows/quality-checks.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Quality
    uses: ./.github/workflows/quality-checks.yml
    with:
      service: shared-messaging-kafka