name: SonarQube

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: sonarqube-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    name: Scan
    uses: vertyll/sonarqube-local/.github/workflows/scan.yml@main
    with:
      java: true
    secrets: inherit
